// --- Abbreviations ---
#align(center)[= LIST OF ABBREVIATIONS]
#table(
  columns: (1fr, 3fr),
  stroke: none,
  align: (left, left),
  column-gutter: 10pt,
  table.header([*Abbreviation*], [*Description*]),
  [*ASR*], [Automatic Speech Recognition],
  [*AUROC*], [Area Under the Receiver Operating Characteristic Curve],
  [*AUPRC*], [Area Under the Precision-Recall Curve],
  [*BERT*], [Bidirectional Encoder Representations from Transformers],
  [*Bi-LSTM*], [Bidirectional Long Short-Term Memory],
  [*CNN*], [Convolutional Neural Network],
  [*CTC*], [Connectionist Temporal Classification],
  [*GPU*], [Graphics Processing Unit],
  [*GUI*], [Graphical User Interface],
  [*HMM*], [Hidden Markov Model],
  [*HuBERT*], [Hidden-Unit BERT],
  [*isWER*], [Intended Speech Word Error Rate],
  [*LLM*], [Large Language Model],
  [*LPC*], [Linear Predictive Coding],
  [*LSTM*], [Long Short-Term Memory],
  [*MFCC*], [Mel-Frequency Cepstral Coefficients],
  [*PCA*], [Principal Component Analysis],
  [*PWS*], [People Who Stutter],
  [*RAG*], [Retrieval-Augmented Generation],
  [*ReLU*], [Rectified Linear Unit],
  [*RNN*], [Recurrent Neural Network],
  [*Sep-28k*], [Stuttering Event Prediction Dataset (28,000 samples)],
  [*SLP*], [Speech-Language Pathologist],
  [*SOTA*], [State of the Art],
  [*SVM*], [Support Vector Machine],
  [*TTS*], [Text-to-Speech],
  [*UAR*], [Unweighted Average Recall],
  [*UI*], [User Interface],
  [*VITS*], [Variational Inference with Adversarial Learning for end-to-end Text-to-Speech],
  [*WavLM*], [Wave Language Model],
  [*WER*], [Word Error Rate],
  [*YOLO*], [You Only Look Once],
)

#pagebreak()
