"""Pure HTML builder for the assessment report. No Qt imports — keep it that way."""

import html
from datetime import date

CLASS_NAMES = ["prolongation", "block", "soundrep", "wordrep", "interjection"]
DISPLAY_NAMES = [
    "Prolongation",
    "Block",
    "Sound Repetition",
    "Word Repetition",
    "Interjection",
]
LANGUAGE_NAMES = {
    "english": "English",
    "kannada": "ಕನ್ನಡ (Kannada)",
    "hindi": "हिंदी (Hindi)",
}

_CSS = """
body { font-family: Georgia, 'Times New Roman', serif; color: #1C1B1F; margin: 0; }
.header { border-bottom: 3px solid #6750A4; padding-bottom: 8px; margin-bottom: 16px; }
.brand { font-size: 26px; font-weight: bold; letter-spacing: 2px; }
.tagline { font-size: 12px; color: #49454F; }
h1 { font-size: 18px; margin: 0 0 4px 0; }
.subtitle { font-size: 12px; color: #49454F; margin: 0 0 16px 0; }
h2 { font-size: 14px; margin-top: 20px; }
table { width: 100%; font-size: 11px; margin-bottom: 8px; border-collapse: collapse; }
th, td { border: 1px solid #CAC4D0; padding: 4px 8px; text-align: left; }
th { background-color: #EADDFF; }
.k { font-weight: bold; width: 40%; }
.meta td.k { background-color: #F3EDF7; }
.transcript { font-size: 12px; line-height: 1.5; }
.severity { font-weight: bold; }
.footer { margin-top: 24px; padding-top: 8px; border-top: 1px solid #CAC4D0; font-size: 10px; color: #49454F; }
"""


def severity_for(results: dict) -> str:
    """Return a de-medicalized severity label from the classification results."""
    classifications = results.get("classifications", {})
    detected = [conf for _name, (is_detected, conf) in classifications.items() if is_detected]
    if not detected:
        return "Fluent"
    top_conf = max(detected)
    if top_conf >= 0.75:
        return "Severe"
    if top_conf >= 0.60:
        return "Moderate"
    return "Mild"


def _class_table_rows(classifications: dict) -> str:
    rows = []
    for name, display in zip(CLASS_NAMES, DISPLAY_NAMES):
        if name not in classifications:
            continue
        detected, conf = classifications[name]
        rows.append(
            f"<tr><td>{html.escape(display)}</td>"
            f"<td>{'Yes' if detected else 'No'}</td>"
            f"<td>{conf * 100:.0f}%</td></tr>"
        )
    return "\n".join(rows)


def _localization_html(localizations: list) -> str:
    if not localizations:
        return "<p>No dysfluency events localized.</p>"
    rows = []
    for i, (start, end, conf) in enumerate(localizations, start=1):
        rows.append(
            f"<tr><td>{i}</td><td>{start:.2f} s</td><td>{end:.2f} s</td>"
            f"<td>{end - start:.2f} s</td><td>{conf * 100:.0f}%</td></tr>"
        )
    return (
        "<table><tr><th>#</th><th>Start</th><th>End</th><th>Duration</th><th>Confidence</th></tr>"
        + "\n".join(rows)
        + "</table>"
    )


def build_report_html(
    results: dict,
    *,
    filename: str,
    language: str,
    duration_sec: float,
    patient_name: str = "",
    report_date: str | None = None,
) -> str:
    """Build a standalone HTML document for the assessment report."""
    report_date = report_date or date.today().isoformat()
    language_display = LANGUAGE_NAMES.get(language, language.title())

    classifications = results.get("classifications", {})
    localizations = results.get("localizations", [])
    transcription = results.get("transcription") or {}
    transcript_text = (transcription.get("text") or "").strip()
    if not transcript_text:
        transcript_text = "No transcription available."

    patient_row = ""
    if patient_name.strip():
        patient_row = (
            f'<tr><td class="k">Patient Name</td>'
            f"<td>{html.escape(patient_name.strip())}</td></tr>"
        )

    severity = severity_for(results)

    meta_rows = f"""{patient_row}
<tr><td class="k">Audio File</td><td>{html.escape(filename)}</td></tr>
<tr><td class="k">Language</td><td>{html.escape(language_display)}</td></tr>
<tr><td class="k">Duration</td><td>{html.escape(f"{duration_sec:.2f} s")}</td></tr>
<tr><td class="k">Assessment Date</td><td>{html.escape(report_date)}</td></tr>"""

    transcript_html = html.escape(transcript_text).replace("\n", "<br>")

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Swaraaha Assessment Report</title>
<style>
{_CSS}
</style>
</head>
<body>
<div class="header">
  <div class="brand">SWARAAHA</div>
  <div class="tagline">Speech Dysfluency Detection</div>
</div>
<h1>Speech Dysfluency Assessment Report</h1>
<p class="subtitle">Automated analysis generated by Swaraaha</p>

<h2>Recording Details</h2>
<table class="meta">
{meta_rows}
</table>

<h2>Classification Results</h2>
<table>
<tr><th>Class</th><th>Detected</th><th>Confidence</th></tr>
{_class_table_rows(classifications)}
</table>

<h2>Localized Dysfluency Events</h2>
{_localization_html(localizations)}

<h2>Summary</h2>
<p>Overall severity: <span class="severity">{severity}</span>. This report summarizes the dysfluency patterns detected in the provided speech sample. If you have concerns, we recommend consulting a qualified speech-language professional for a formal evaluation.</p>

<h2>Transcript</h2>
<p class="transcript">{transcript_html}</p>

<div class="footer">
Generated by Swaraaha on {html.escape(report_date)}. This report summarizes automated dysfluency detection output and is not a medical diagnosis; consult a qualified speech-language professional for a formal evaluation.
</div>
</body>
</html>"""
